version: "3"

services:
  app:
    image: wordle-slack-bot_app 
    container_name: worlde_bot
    restart: always
    build: .
    environment:
      - NODE_ENV=.env
      - TZ=Europe/Amsterdam
    ports: 
      - "3000:3000"
